#! /bin/sh

if ! snapctl is-connected hardware-observe; then
	logger -t $SNAP_NAME "hardware-observe not connected yet, doing nothing"
	exit 0
fi

logger -t $SNAP_NAME "all interfaces connected, starting pulseaudio service"

snapctl start $SNAP_NAME.pulseaudio --enable
